### ISSUE TITLE
Problem of make clean

### ISSUE THREAD

**Issue by skhokhlov** [Arquestro/neptune#1]
У тебя команда clean ничего не удалит

```makefile
OUT_EXE = main
```
```makefile
clean:
	rm -f *.o
```
https://github.com/Arquestro/neptune/blob/master/makefile

**Comment by Arquestro** [comment]
Это если объектов нет в папке мэйкфайла.
Шаблоны, Серега, шаблоны на будущее ведут к успеху.

**Comment by skhokhlov** [comment]
Тема, если бы ты знал, кому ты это говоришь. Если бы ты знал, как я заморачивался с шаблонизацией.
